### ISSUE TITLE
Less accuracy

### ISSUE THREAD

**Issue by sumitthorat** [lightsalsa251/Diabetic-Retinopathy-with-CNN#1]
I'm trying to re run your code but the accuracy is very less (Approximately 17%). Can you please provide some insights and also share your trained model? Thanks.
My email : sumit.thorat97@gmail.com

**Comment by Iammuratc** [comment]
I just wanted to ask if you get any better results. I also want to use the model, but not sure how good it is. I don't want to waste time if it doesn't work at all...

Thanks.
